[package]
name = "athena"
version = "0.1.0"
edition = "2021"


[dependencies]
patternfly-yew = "0.6.3"
yew = { version = "0.21", features = ["csr"] }

[dependencies.web-sys]
version = "0.3"
features = [
    "HtmlElement",
    "HtmlInputElement",
    "MediaQueryList"
]
